### ISSUE TITLE
UX Design issue: Road Conditions

### ISSUE THREAD

**Issue by abquirarte** [cagov/UX#104]
## Notes from testing: 
https://docs.google.com/document/d/1PY0c1R-aPWnaY0_PIfm3stLl8WLCsfrZajTVn2kY7YQ/edit

- Content organization reviewed from Design perspective 
- User interaction discussed and documented 
- Wireframes iterated and finalized (If applicable)
- Design system discrepancies minimized
- Design and UX issues documented and resolved

**Links to parent user story and prototype issue(s)**
Parent: https://github.com/cagov/UX/issues/37 
UX prototype Issue: https://github.com/cagov/UX/issues/86 
User Testing Issue: https://github.com/cagov/UX/issues/91

**Link to UX prototype or CWDS template page(s)**
https://cagov.github.io/UX/caltrans/

**Comments on content information architecture and Organization**
- Comments:

- Reorder table results to be: 1. Location, 2. lane closures, 3. road condition/description
- Capitalize the "near" in the table results
- Animated scroll 
- Get rid of placeholder text "search"
- NO ~~Hide the text box after the user has entered their address.~~
- NO, just X ~~**Show the address entered along with an "Edit" link that would take them back to a text box**~~
- **Buttons after each form field**
- Links to maps that show lane closures   (maybe)
- **Get directions button (opens up your native map or gives options: Google Maps, Apple Maps)**

- [x] remove CHP
- [x] put both fields 

**Wireframe comments and location**
- Applicable link(s)
- Comments:

**User interaction feedback and links**
- Applicable link(s)
- Comments:

**Design system issues**
- Applicable link(s)
- Comments:

**Comment by aaronhans** [comment]
Remaining todo items from pre user testing list:

- [ ] Add error message for when a user enters saldfjhdskjfh: "Please enter a valid city or zip code, such as San Francisco or 95818."
- [ ] Add disclaimer message for when a user enters in an address outside of California: "Please note: We can only share the road conditions on the part of your trip within California."
- [ ] form inputs need labels, review HTML structure
- [ ] changing previously entered destination before changing starting point should reset obstructions to match new route
- [ ] add directions button at bottom of results that links to mapping application sending all params required to write reports
- [ ] add calls to road closures
- [ ] add calls to CHP incidents
- [ ] add locate me

**Comment by aaronhans** [comment]
One more item from out pokemon trainer subject that seemed like a good idea but that the group should consider before we implement:

- [ ] show all the major highways roads on the way, even if there are no issues on them so you know that those steps in your trip are clear

**Comment by abquirarte** [comment]
Notes from testing here: https://docs.google.com/document/d/1gI7FTXRLmv32825eBof_euiH4NquYlHMpFgYlyDLRIk/edit

**Comment by aaronhans** [comment]
Final list of todo items for next round of user testing:

- [ ] add button to both search fields using the text enter
- [ ] add button at bottom which links to google maps directions
- [ ] get rid of the placeholder text in form fields
- [ ] get rid of the displayed destination and starting address HTML elements (user will only view and edit those values inside the input fields)
