### ISSUE TITLE
Content prototype: Check your eligibility for LifeLine

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#105]
- [x] meta description
- [x] page title
- [x] [Google doc](https://docs.google.com/document/d/1-qswgufS5Ic0qHTEfFf_G3prESde7KGqXG7CMXS5ZIY/edit)
- [ ] Listen to it through a screen reader
- [x] Check for header structure
- [x] URL structure

**Comment by abquirarte** [comment]
UX prototype issue: https://github.com/cagov/UX/issues/82
