### ISSUE TITLE
Content prototype: Apply online for LifeLine

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#106]
- [x] meta description
- [x] page title
- [x] [Google doc](https://docs.google.com/document/d/1L6MCHVgkt9K--F7mwyaR45pIZqJ3cY_Ze-nO_IAShs0/edit#)
- [ ] Listen to it through a screen reader
- [x] Check for header structure
- [x] URL structure

**Comment by abquirarte** [comment]
UX prototype issue: https://github.com/cagov/UX/issues/82
