### ISSUE TITLE
UX prototype: Apply online for LifeLine 

### ISSUE THREAD

**Issue by artuoma** [cagov/UX#109]
**Parent User Story:** https://github.com/cagov/UX/issues/64

**content prototypes:** 
#106

**Prototype Link(s):** 
-- https://cagov.github.io/UX/apply-online-discounted-phone-service

- [ ] HTML page(s) created and linked in UX repo
- [ ] Meta description added 
- [ ] Page title updated
- [ ] Content integrated according to design system and standards 
- [ ] Automated accessibility checks performed (score of 100%)
- [ ] Manual accessibility checks performed ([See checklist](https://drive.google.com/open?id=0B72FqFUONAggazJwQURQeTBPMEZGRjJXSFNGcDJrMF9ENERR))
- [ ] HTML structure verified
- [ ] Design issue template # (Closed)
- [ ] Migrated to Alpha repo

**11y Status:** Issues and resolution status if applicable

**Design Issue Link:** Link to Design issue if applicable#

**Comment by abquirarte** [comment]
going to close for this sprint

cc @KimberlyglennTSM
