### ISSUE TITLE
EDD/Unemployment Insurance Qualitative Discussion guide

### ISSUE THREAD

**Issue by hilaryhb** [cagov/UX#11]
As a newly laid-off person, I need to file for unemployment insurance so that I have enough money to live (and the form is only available online during business hrs)

- [x] Create screener for EDD

- [x] Create and send email to Angie to pass to EDD

- [x] Create discussion guide

**Comment by hilaryhb** [comment]
[Screener](https://www.surveymonkey.com/r/EDD1) for uneployment PFL, and caring for an ill family member.

**Comment by hilaryhb** [comment]
[Discussion guide](https://docs.google.com/document/d/17rPMCJEcbsz4-dMdZqOv6JFBTMT-eAfSHohly4fuHE0/edit#) for longer, scheduled 45 min and shorter, in office one. The in office one will be very informal and really just talking to people about what brought them into the office that day. Will try for 12/18 SAC EDD office visit.

**Comment by hilaryhb** [comment]
@abquirarte can I close this or do you need to?

**Comment by abquirarte** [comment]
I've reviewed and I'm closing 👍
