### ISSUE TITLE
Content research: Wildfire - alerts 

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#110]
#### [Content Research Folder](https://drive.google.com/drive/u/0/folders/1IPVcvz2WVUl01tnyuAMI9YEJr-Cil5CA)

- [x] Create a [spreadsheet](https://docs.google.com/spreadsheets/d/1x6i-_GdULub-Hyhh-w8pb639lFamHfFM3XKsr6px5Nc/edit#gid=0)
- [ ] Reach out to a subject matter expert? (@abquirarte )

**Comment by humancenteredhuman** [comment]
@hilaryhb and @KimberlyglennTSM have started putting their research in a spreadsheet. (thanks!)

**Comment by abquirarte** [comment]
> @hilaryhb and @KimberlyglennTSM have started putting their research in a spreadsheet. (thanks!)

Adding hyperlinks and referencing the main story :)

**Comment by abquirarte** [comment]
Closing this. It's a duplicate. Updated here: https://github.com/cagov/UX/issues/30
