### ISSUE TITLE
Content research: Wildfire - Remove debris

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#113]
- [x] Create a [folder](https://drive.google.com/drive/u/0/folders/1zAlR6-IkT9NbcwXksfyhQ9CMKKjJcaGM). 
- [x] Reach out to a subject matter expert? (@abquirarte @KimberlyglennTSM  )

**Comment by humancenteredhuman** [comment]
@KimberlyglennTSM to reach out to Department of Toxic Substances Control (DTSC)

**Comment by abquirarte** [comment]
closing, for now. 
Follow-up should be with CalRecycle as needed.
