### ISSUE TITLE
Content research: Wildfire - dispose of a burnt car

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#114]
#### [Content Research Folder](https://drive.google.com/drive/u/0/folders/14nCdd28E6GHEIzPZVGMIpzXLW7Tl3TfC)

- [x] Create a [spreadsheet. ](https://docs.google.com/spreadsheets/d/1FMOLLkLAs5ngheVHbpH1J1LWxst9S3KNqR8BoZAsG7o/edit#gid=0)
- [x] Reach out to a subject matter expert (@abquirarte reached out 2/9/2020 to DMV SME. Asked to set up 30 min call)

**Comment by abquirarte** [comment]
Started the spreadsheet @humancenteredhuman : 

https://docs.google.com/spreadsheets/d/1FMOLLkLAs5ngheVHbpH1J1LWxst9S3KNqR8BoZAsG7o/edit#gid=0

**Comment by abquirarte** [comment]
✅
