### ISSUE TITLE
Content prototype: Apply for unemployment insurance 

### ISSUE THREAD

**Issue by artuoma** [cagov/UX#118]
**Parent User Story:** https://github.com/cagov/UX/issues/100
**Prototype Link(s):** Link in Proggress

- [x] Wireframes iterated and finalized (If applicable)
- [x] HTML page(s) created and linked in UX repo
- [x] Meta description added 
- [x] Page title updated
- [x] Content integrated according to design system and standards 
- [x] Automated accessibility checks performed (score of 100%)
- [x] Manual accessibility checks performed ([See checklist](https://drive.google.com/open?id=0B72FqFUONAggazJwQURQeTBPMEZGRjJXSFNGcDJrMF9ENERR))
- [x] HTML structure verified
- [x] Design issue template # (Closed)
- [x] Migrated to Alpha repo

**11y Status:** Issues and resolution status if applicable

**Design Issue Link:** Link to Design issue if applicable#

**Comment by abquirarte** [comment]
closing- since this is now live.
