### ISSUE TITLE
User story - State Holidays

### ISSUE THREAD

**Issue by hilaryhb** [cagov/UX#12]
As a State employee 
I need to know which days are official holidays 
so that I make personal plans

- [x] (#15 ) Content prototype

- [x] (#16 ) Content research

- [x] Field test A/B "Next Holiday" and simple, fast, clear 12/18
Questions:
1. How do people feel about the “Next holiday” card
2. Do people care/want an icon for the “adding to calendar” option
3. Do people care/want the “adding to calendar” link
4. Is there any information missing?
5. Is it too much information? 
6. How does it compare to the existing page from CAlHR? 

- [x] Capture [feedback](https://docs.google.com/document/d/1vh86JVWfqeuyCZH3Xl6vcflXzP5UifWTsgqmZM6-3pw/edit#)

**Comment by artuoma** [comment]
I uploaded some prototypes under (#15)
