### ISSUE TITLE
Content prototype: Wildfire - preparedness

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#121]
- [x] meta description
- [x] page title
- [x] [Google doc](https://docs.google.com/document/d/1e9ctIES3N0nJkD6QINhZ_uEB_ryNiOhht5EmSVWLpn8/edit#) 
- [ ] Listen to it through a screen reader
- [x] Check for header structure
- [x] URL structure

**Comment by abquirarte** [comment]
closing!
