### ISSUE TITLE
Content prototype: Wildfire recovery

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#122]
- [x] meta description
- [x] page title
- [x] [Google doc](https://docs.google.com/document/d/1UskVqQMWF_F8OFWP2mm3bdwXg4yB3bDSyn0WpUqjTu0/edit#) 
- [ ] Listen to it through a screen reader
- [x] Check for header structure
- [x] URL structure

**Comment by abquirarte** [comment]
closing for this iteration
