### ISSUE TITLE
UX prototype alerts

### ISSUE THREAD

**Issue by aaronhans** [cagov/UX#123]
**Parent User Story:**
https://github.com/cagov/UX/issues/36

**Prototype Link(s):** 
https://cagov.github.io/UX/alerts/

- [x] Wireframes implemented
- [ ] HTML page(s) created and linked in UX repo
- [ ] Meta description added 
- [ ] Page title updated
- [ ] Automated accessibility checks performed (score of 100%)
- [ ] Manual accessibility checks performed ([See checklist](https://drive.google.com/open?id=0B72FqFUONAggazJwQURQeTBPMEZGRjJXSFNGcDJrMF9ENERR))

**Comment by aaronhans** [comment]
- [ ] build new API that resolves county from zip code
- [ ] update alert search logic to hit new api when numbers are entered
- [ ] fix error message alignment

**Comment by abquirarte** [comment]
closing, update original as needed. Thanks!
