### ISSUE TITLE
UX and Design Actions

### ISSUE THREAD

**Issue by abquirarte** [cagov/UX#124]
Documenting part of our conversation

## Unemployment

- [x] flip navigation so it shows up at the top on mobile 
**Note** - we made the decision to move the navigation to the left because it picks up first on screenreaders. 

- [x] [ See notes](https://docs.google.com/document/d/1dvy3BQiiNHL0ikBMs2pLbsVbP6Sr73odSGOa8703UF0/edit) from testing, we may want to soften language ("totally") 

- [x] Expand all of the UI guide (make a single html page with content of all steps so that people can see them all in one, since right now each step is a single page)

- [x] make sure "step" links to proper content on mobile

![UI mobile version- 2-19-2020](https://user-images.githubusercontent.com/9556188/74870511-b6381e00-530e-11ea-9e8e-987bb808791d.jpg)

## Water

- [x] Check on the use of word "safe"
- [x] move side bar content to main page - make sure it's accessible - ~example of accordion: https://www.alpha.ca.gov/state-california-employee-holidays/~ 
- [ ] Check semantics 
- [x] Keep x Bar
- [ ] User test

## Alerts 

- [x] match to county and zipcode
- [x] fix error message (when button moves)

## Lifeline 

- [x] Extend gray shade below the description, much like what Art did with unemployment insurance

## Org 

GovOps Contact page is wrong- it now points to https://www.govops.ca.gov/contact-us-2/ and it should point to: https://www.govops.ca.gov/contact-us/ 

- moved to Alpha #387 

--------------------------

**Parent User Story:** Link to parent user story
**Prototype Link(s):** Link to UX prototype page

- Wireframes iterated and finalized (If applicable)
- HTML page(s) created and linked in UX repo
- Meta description added 
- Page title updated
- Content integrated according to design system and standards 
- Automated accessibility checks performed (score of 100%)
- Manual accessibility checks performed ([See checklist](https://drive.google.com/open?id=0B72FqFUONAggazJwQURQeTBPMEZGRjJXSFNGcDJrMF9ENERR))
- HTML structure verified
- Design issue template # (Closed)
- Migrated to Alpha repo

**11y Status:** Issues and resolution status if applicable

**Design Issue Link:** Link to Design issue if applicable#

**Comment by koryfey** [comment]
Fixed lifeline and unemployment items. Pushed my changes to repository master.

**Comment by abquirarte** [comment]
Closing this issue now. 
New design needs for release 3 will be documented in https://github.com/cagov/Alpha/issues/387
