### ISSUE TITLE
User Testing: 10 considerations for Wildfire Recovery

### ISSUE THREAD

**Issue by abquirarte** [cagov/UX#125]
## Link to main user story Github Issue: 
Recover: https://github.com/cagov/UX/issues/99

## Content type being tested: 
Step by Step

## Who is testing and when: 
We are testing via usertesting.come 2/25/2020

## **Things to Test for:**

- How do people react to word step?
- Do they think these have to be done in order?
- Is there something they don't understand?
- Are any of these steps something you wouldn't have thought to do? Which ones?

## **Link to insights** -
[Feedback Doc here 2_25_2020](https://docs.google.com/document/d/1L68gWqMSW11aX8njfZ3_Rabecim3EHCSbhvce2ibf_s/edit)

**Comment by hilaryhb** [comment]
@abquirarte @lukefretwell @artuoma @aaronhans feedback from 3 tests is in - see linked doc above

**Comment by abquirarte** [comment]
✅
