### ISSUE TITLE
User Testing: 10 steps to prepare for a wildfire

### ISSUE THREAD

**Issue by hilaryhb** [cagov/UX#126]
Link to main user story Github Issue: #98 
Content type being tested: Step by Step
Who is testing and when:  We are testing via usertesting.com 2/25

**Things to Test for:**
- Does the order make sense
- Do people think they have to complete all steps
- Do people trust CA to deliver this information
- Does Step 2 make sense
- Does Step 3 apply to everyone
- We reference "emergency kit" in step 4 but no where else and then step 5 is gather supplies
- Need Step 8
- What might be unclear?
- What, if anything, did people learn that is new?
- How prepared do people feel now? And after reading this?

**Link to insights**
[Feedback from usertesting.com](https://docs.google.com/document/d/1vebH3YHcFnxtSD6SNzhgUWK2B8azdkZllyvnt68PSac/edit#)

**Comment by abquirarte** [comment]
✅
