### ISSUE TITLE
Lifeline Qualitative Research Plan

### ISSUE THREAD

**Issue by hilaryhb** [cagov/UX#14]
As a person who has very limited income
I need to know what lifeline services are available
so that I can get by month to month

- [x] Attend SME mtg w Mike 12/12 - done

- [x] Capture notes and ideas for UI feedback - 

- [x] Craft plan here - N/A since it's just info. 

- [x] Gather content/information

**Comment by abquirarte** [comment]
Closing this. Must make sure we test against lifeline phones as many user stories as possible!
