### ISSUE TITLE
State Holidays: Content prototype

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#15]
- [x] Write content mockup. 

- [x] Get a second pair of eyes. 

- [x] Hand off to designers/dev.

- [x] Adding anchor link for July 4. @artuoma 

- "July 4 ([holiday credit](#))      Saturday      Independence Day"
[Prototype version to use](https://github.com/cagov/UX/blob/master/docs/state-holidays/v2.html)

**Comment by artuoma** [comment]
![State Holidays - Window@2x](https://user-images.githubusercontent.com/20782462/71043004-2b565f80-20e2-11ea-83a5-48ca9d55887f.png)
![State Holidays - Phone@2x](https://user-images.githubusercontent.com/20782462/71043005-2b565f80-20e2-11ea-9856-584dabf4d222.png)

**Comment by artuoma** [comment]
A quick prototype, very similar to what @humancenteredhuman and @aaronhans  have created.

**Comment by KimberlyglennTSM** [comment]
Reviewed and approved.
