### ISSUE TITLE
State Holidays: Content research

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#16]
- [x] Research existing information on state holidays

**Comment by humancenteredhuman** [comment]
- Existing page: https://www.calhr.ca.gov/employees/pages/state-holidays.aspx
Notes: 
- When a holiday falls on a Saturday, employees get holiday credit.
- When a holiday falls on a Sunday, employees have the day off on the following Monday.
- Excluded employees get one personal holiday each fiscal year (July 1 to June 30). 

GOV.UK example: https://www.gov.uk/bank-holidays#northern-ireland

**Comment by humancenteredhuman** [comment]
[Search console data](https://search.google.com/u/1/search-console/performance/search-analytics?resource_id=sc-domain%3Aca.gov&num_of_months=16&page=!https%3A%2F%2Fwww.calhr.ca.gov%2Femployees%2Fpages%2Fstate-holidays.aspx&compare_page=https%3A%2F%2Fwww.dir.ca.gov%2Fdlse%2Ffaq_minimumwage.htm&metrics=CLICKS).

Top three keyword searches: 

- california state holidays | 1,459 clicks

- state holidays 2019 | 1,259 clicks

- california state holidays 2019 | 814 clicks

**Comment by KimberlyglennTSM** [comment]
Reviewed and approved.
