### ISSUE TITLE
Minimum wage: Iterate on content prototype

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#17]
- [x] Iterate on content prototype based on user research. 

- [x] Changing the dates into accordions. (@artuoma)
[Prototype version to work from](https://cagov.github.io/UX/mw/). 
https://github.com/cagov/UX/blob/master/docs/mw/index.html

- Link text: "Minimum wage increases on Jan. 1, 2020"

- Link text: "Minimum wage increases on July 1, 2020"

- [x] #26 Add helper text.

**Comment by KimberlyglennTSM** [comment]
Reviewed and closed.
