### ISSUE TITLE
Victim of Fire/Trauma Research Study (Field Trip)

### ISSUE THREAD

**Issue by hilaryhb** [cagov/UX#21]
As a survivor of a wildfire, I need find state opportunities so that I can rebuild my life

- [x] Figure out best way to recruit/w Angie

- [x] Select and schedule participants (in process)

- [x] Conduct interviews

- [x] Design, plan and schedule field trip to Paradise

- [x] Team field research trip to Paradise (1/29)

- [x] Synthesize and pull out stories, quotes and insights

**Comment by abquirarte** [comment]
https://www.gov.ca.gov/2019/08/20/governor-newsom-announces-launch-of-50-million-listos-california-campaign-to-help-build-community-resilience-to-wildfires/

**Comment by abquirarte** [comment]
https://docs.google.com/document/d/1BJ_R_pt0gTq2aovmNNhWTr9U2Og7Kq3KNuIzUjacXXE/edit?ts=5e30bb2a#
