### ISSUE TITLE
Incorporate page meta components into content prototyping process

### ISSUE THREAD

**Issue by lukefretwell** [cagov/UX#22]
For content structure and search engine optimization purposes, we should incorporate meta content into the prototyping process so we ensure these elements are strategically developed and added to each page.

References: 

* Page title: https://moz.com/learn/seo/title-tag
* Meta description: https://moz.com/learn/seo/meta-description

**Comment by humancenteredhuman** [comment]
Luke helped me add meta description as a checkbox to the [content prototyping issue template](https://github.com/cagov/UX/issues/new/choose).
