### ISSUE TITLE
Minimum wage: Add helper text if someone enters "xyz" as a city. 

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#26]
If someone enters an invalid zip code or city, we'll want red helper text (or whatever color the designers choose) to appear to the side (or wherever the designers choose). 

"Please enter a city or zip code in California."

**Comment by abquirarte** [comment]
@aaronhans @lukefretwell 
thoughts on this?

**Comment by aaronhans** [comment]
I am ready to implement this, I will use the default styles here https://cwds.dev/docs/4.3/forms/validation/ unless anybody wants to provide additional design guidance cc @artuoma

**Comment by aaronhans** [comment]
link: https://cagov.github.io/UX/mw/
