### ISSUE TITLE
Content prototype: Hire a licensed contractor

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#27]
As a homeowner, i need to hire a licensed contractor, so that I can make legal upgrades to my home.
https://www.cslb.ca.gov/Consumers/Hire_A_Contractor/Do_It_Right_Video.aspx

- [x] meta description
- [x] page title
- [x] [Google doc](https://docs.google.com/document/d/1gBrXS5IGXfftqtTPxsclCsHiVj_8IwGJGl3GoaBsyME/edit#)
- [x] Listen to it through a screen reader
- [x] Check for header structure
- [x] URL structure

**Comment by abquirarte** [comment]
Link to prototype: https://cagov.github.io/UX/licensed-contractor/
