### ISSUE TITLE
Content research: Hire a licensed contractor

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#28]
As a homeowner, i need to hire a licensed contractor, so that I can make legal upgrades to my home.
https://www.cslb.ca.gov/Consumers/Hire_A_Contractor/Do_It_Right_Video.aspx

- [x] Create a [spreadsheet](https://docs.google.com/spreadsheets/d/19nvfkPACMVHCA1gRE6xDmBLIlu1n6TkRPvgiaj46gu4/edit?folder=1iSOFn7JHHSti-m3CLboeh1lij2ChtyEs#gid=0).
- [x] Contact subject matter experts? (@abquirarte)

**Comment by abquirarte** [comment]
We may have to do better quality fact checking after the holiday!

**Comment by abquirarte** [comment]
Outstanding: We want to flesh out step 2 better. @KimberlyglennTSM 
Can we summarize/better determine who needs a building permit?

**Comment by KimberlyglennTSM** [comment]
@humancenteredhuman and @abquirarte I will send another follow-up to CSLB

**Comment by humancenteredhuman** [comment]
@KimberlyglennTSM @abquirarte Creating a new issue for Kimberly's fact-checking.

**Comment by abquirarte** [comment]
awesome, thank you!

**Comment by abquirarte** [comment]
https://github.com/cagov/UX/issues/75#event-2959212093
