### ISSUE TITLE
Content prototype: Emergency alerts

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#29]
**Main story: UX #36** 

As a Californian, I need to stay in know and be alerted to emergencies so that I can be proactive or know what to do when there is an emergency.

- [ ] meta description
- [ ] page title
- [ ] Google doc (url)
- [ ] Listen to it through a screen reader
- [ ] Check for header structure
- [ ] URL structure

**Comment by abquirarte** [comment]
Sample presentation from DSIA: https://docs.google.com/presentation/d/1k6sEVVM0dRWwCVVjmMA9I6hDKjh7rHlY9KzkfPD7dAY/edit#slide=id.p1

**Comment by abquirarte** [comment]
closing for this iteration
