### ISSUE TITLE
Content research for minimum wage

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#3]
- [x] Gather info on California minimum wage. 

- [x] Create a [spreadsheet](https://docs.google.com/spreadsheets/d/1Z0HN1X7S1m2c0b4UOtBvAnSiYe9Fwb4OigYaSjtnn3I/edit?folder=1k4Lw204zguZL7mO-0Vdhft-cRmDSzOSx#gid=0)

- [x] Check with subject matter experts. 

- [x] Finish spreadsheet

- [x] Finish first round of fact-checking

**Comment by KimberlyglennTSM** [comment]
Reviewed and approved minimum wage content research.
