### ISSUE TITLE
Content research: Emergency alert

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#30]
### Main User Story: https://github.com/cagov/UX/issues/36 

As a Californian, I need to stay in know and be alerted to emergencies so that I can be proactive or know what to do when there is an emergency.

- [x] Create a [spreadsheet](https://docs.google.com/spreadsheets/d/1x6i-_GdULub-Hyhh-w8pb639lFamHfFM3XKsr6px5Nc/edit?folder=1iSOFn7JHHSti-m3CLboeh1lij2ChtyEs#gid=0)

- [x] Folder: https://drive.google.com/drive/u/0/folders/1IPVcvz2WVUl01tnyuAMI9YEJr-Cil5CA

- [x] Reach out to subject matter experts

**Comment by abquirarte** [comment]
Closing.
