### ISSUE TITLE
As a Californian, I need to know what ALERT OPTIONS I have when there are emergencies so that I can get notified

### ISSUE THREAD

**Issue by abquirarte** [cagov/UX#36]
## Content Type  
Calculator (smart answer)/ Location

## Our assumptions, what we want to test/learn
During our visit to Paradise, we continuously heard that people kept checking their phones for alerts. While there are no guarantees alerts will be pushed out in a state of emergency, we assume there is a gap between the number of people that could get alerts and those that are actually signed up for alerts. We want to test if increasing awareness of alerts people could sign up for will make people feel more prepared. 

## **Baseline (use screenshots. Github Issues, Links, and date of when test was conducted)**

**- URL** 
_(Link to current state page)_

**- Speed** 
_(Test for mobile and desktop, include #, add date of when you did the test: https://developers.google.com/speed/pagespeed/insights/)_

**- Accessibility**  
_(Check for mobile and desktop, slowest speed, include score, use Lighthouse in dev tools to trigger an audit on page, see for walk through https://github.com/cagov/Alpha/issues/68#issuecomment-570694179 )_

**- Readability** 
_(Use http://www.hemingwayapp.com/ and take a screenshot include grade)_

## **Process (add links, attachments, DRI, and Github issues)**

- [x] Content Research 
https://github.com/cagov/UX/issues/30 
- [ ] User Research (visit to Paradise)
- [x] Content Prototype 
https://github.com/cagov/UX/issues/29
- [ ] Design Prototype (URLs / issue: https://github.com/cagov/UX/issues/107)
- [ ] Fact Check (where applicable)
- [ ] Accessible (Use Lighthouse in dev tools to trigger an audit on page)
- [ ] Responsive
- [ ] User Tested
- [ ] Iterated
- [ ] Translated
- [ ] Shipped (tested and ready to push to live)
- [x] End to End Testing (automated) https://github.com/cagov/Alpha/pull/461
- [ ] Live 
- [ ] Production Testing

**Comment by abquirarte** [comment]
From Hilary:
![image](https://user-images.githubusercontent.com/9556188/71701001-ca828480-2d7b-11ea-937d-50d432de896a.png)

**Comment by abquirarte** [comment]
Sample from DSIA: https://docs.google.com/presentation/d/1k6sEVVM0dRWwCVVjmMA9I6hDKjh7rHlY9KzkfPD7dAY/edit#slide=id.p1

**Comment by abquirarte** [comment]
Yes that is correct.  Here is the navigation:

 

https://lacounty.gov/

 

-> SUBSCRIBE (bottom of the page)

 
![image](https://user-images.githubusercontent.com/9556188/74207259-b449cd00-4c33-11ea-8f37-aeba4d0e6756.png)


A close up of a sign

Description automatically generated

 

-> govDelivery Opt-in (optional email or SMS text message opt-in) https://public.govdelivery.com/accounts/CALACOUNTY/subscriber/new

 

A screenshot of a cell phone

Description automatically generated

 
![image](https://user-images.githubusercontent.com/9556188/74207244-a1cf9380-4c33-11ea-98be-be9bb2a8a1e3.png)


-> Select topic interest https://public.govdelivery.com/accounts/CALACOUNTY/subscriber/topics

 
![image](https://user-images.githubusercontent.com/9556188/74207234-98462b80-4c33-11ea-80b6-1a7dfb2c023e.png)



The little antenna icon means that the topic is will be notified via SMS text option as well.  

 

You can see there are other topics such as homeless, CalFresh, Dept of Children and Families Services, Census 2020 etc.

**Comment by ChadABratton** [comment]
End to end testing complete.  @abquirarte  @KimberlyglennTSM 
https://github.com/cagov/Alpha/pull/461

![image](https://user-images.githubusercontent.com/28573666/75203057-fe49ad00-5721-11ea-92d6-01d57a268ca3.png)

**Comment by abquirarte** [comment]
NIce!
