### ISSUE TITLE
Content prototype for minimum wage

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#4]
- [x] Write new mockup of [minimum wage explainer]([Current state](https://www.dir.ca.gov/dlse/faq_minimumwage.htm))
([Mockups](https://github.com/cagov/UX/tree/master/docs/mw))

- [x] Hand off to design/dev for content types and development.

**Comment by abquirarte** [comment]
@lukefretwell and @aaronhans can you please 👀 this and give me 👍 ? I want to close.

**Comment by lukefretwell** [comment]
@abquirarte @humancenteredhuman @aaronhans are there actual links to the page (and not just code)?

**Comment by aaronhans** [comment]
Last I heard we were done with our rounds of user testing and this is the latest version https://cagov.github.io/UX/mw/ so we can move on to making sure it is accessible and performant and migrate it to the alpha repository which should be a separate ticket. I don't believe there are any outstanding items for a UX prototype for this page so we can close this. I know we have to come up with a plan on how to integrate pages like this into more of a full fledged site

**Comment by humancenteredhuman** [comment]
Sorry for any confusion — after we finished the first prototype and did user testing, I created an [issue for iteration on minimum wage](https://github.com/cagov/UX/issues/17). I imaged this current issue (#4) as finishing the prototype before testing. 

Please let me know if you think I should consolidate prototyping and iteration into one issue in the future, or keep them separate. Thanks!

**Comment by KimberlyglennTSM** [comment]
Hi @humancenteredhuman  - Yes, in the future lets consolidate prototyping and iteration into one issue.  Start next a new issue with next cycle/iteration. Please let me know if I don't make sense. Thanks
