### ISSUE TITLE
Food bank prototype refinement

### ISSUE THREAD

**Issue by aaronhans** [cagov/UX#40]
User Story: #33 

Following updates should be made to: https://cagov.github.io/UX/food/v0.html so we can get to a good v1 version we can show to users. This list is from @artuoma @humancenteredhuman and @aaronhans 

- [x] place results into cards:https://getbootstrap.com/docs/4.4/components/card/
- [x] Instead of "Nearest results," it could say something like "Food banks near 95816" or "Food banks near Auburn, CA." It confirms to the user what they've entered.
- [x] but a quicker improvement would be: Have a get directions button on the map location info label 
  (for example Open with : Google Maps , Apple Maps etc…)
  Each results should have a “Open in Maps” link as a button, or get directions
- [x] We'll also want a button/CTA under the text input: "See food near you"
- [x] from a usability and A11y perspective you wouldn’t spell out a complete URL to the foodbank website but instead: Visit Sunrise Christian Food Ministry’s website
  OR Visit the Food Bank website and use the ARIA label to add the full name from the result’s title for A11y
  and append it to the link title
- [x] add more data, pull from LA, SF APIs, 211 county resources, foodpantries.org and https://www.cdss.ca.gov/food-banks food bank list
- [x] clicking on map markers should display all site info in popup
- [x] truncate distance measurement to two decimal places
- [x] setup twilio number to accept text messages and return nearby results
- [x] make cards fit side by side on larger screens, collapse columns responsively

**Comment by aaronhans** [comment]
Going to postpone this one, it is totally doable, but with current page layout you probably can't see both map and your highlighted item:

- [ ] you could see if the card could be connected to the map so it is highlighted if clicked on the map but this would only be useful on desktop

**Comment by aaronhans** [comment]
Would like help from @artuoma on this item:

- [ ] need better map marker image

**Comment by aaronhans** [comment]
Added a lot of functionality, may be ready for user testing (SMS response still only works on verified numbers until we subscribe)

**Comment by aaronhans** [comment]
Additional AMS requirements:
- [ ] needs to respond with "Sorry, we don't recognize that city. Please text us a California city or zip code." if city cannot be parsed from initial input
- [ ] needs to respond to "STOP" text with language fulfilling legal requirements even though we are not subscribing them to updates

**Comment by aaronhans** [comment]
- [ ] We've got some design issues with this page, need to fix colorful stuff to conform to style guid

**Comment by abquirarte** [comment]
Ok! 
@KimberlyglennTSM can you add SMS/Twilio upgrade to our ops repo for tracking?
