### ISSUE TITLE
Fact-check Cal Grant

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#44]
- [x] Talk/email with subject matter expert

**Comment by abquirarte** [comment]
Rebecca was able to connect with someone else to do initial fact-checking (FUSE contacts from jcs) 

We can do "final" fact check with CSAC this week, waiting for them to get back to us.

**Comment by abquirarte** [comment]
Sent another reminder to the scheduler today 1/7/2020 9:25 am

**Comment by abquirarte** [comment]
Scheduled for Friday 1/10 at 3pm

**Comment by KimberlyglennTSM** [comment]
Had a call 1/10- received good feedback on process. Changing steps based on that feedback
