### ISSUE TITLE
Angie to add state holidays and birth certificate user needs to template

### ISSUE THREAD

**Issue by KimberlyglennTSM** [cagov/UX#45]
referencing: https://github.com/cagov/Alpha/issues/72 

We need to make sure we have the baseline for each of these prior to release 1

https://cagov.github.io/UX/state-holidays/v2
https://cagov.github.io/UX/mw/v6
https://cagov.github.io/UX/birth-certificate

**Comment by abquirarte** [comment]
Added. Just need to finish populating the content for documentation. @orielgomez @KimberlyglennTSM is this something you can both help with? 
I'm basically filling in the blanks (testing URL links, speed, accessibility, readability, screenshots)
