### ISSUE TITLE
User Test Food Bank Prototype

### ISSUE THREAD

**Issue by KimberlyglennTSM** [cagov/UX#46]
- [x] Create testing guidelines
- [x] Document Feedback ([Google Doc](https://docs.google.com/document/d/14mSslB3Cn6Ts7tRTcwJJSdfnSSXOzO2U/edit))
- [x] Rebecca to Iterate on feedback (#49 )

Main user story: https://github.com/cagov/UX/issues/33 

[Test script](https://docs.google.com/document/d/1ONK5gvD7QHbI1lLG5pGAK23ui-EInGz8QVT0Gl84aq4/edit#heading=h.oakblna6evue) - added 1/7 by Hilary

**Comment by hilaryhb** [comment]
@abquirarte @KimberlyglennTSM can close this
