### ISSUE TITLE
Iterate on content: Cal Grant

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#47]
- [x] Digest user testing
- [x] Iterate on content based on feedback

**Comment by humancenteredhuman** [comment]
Iterated on content based on user feedback (#35 )
https://cagov.github.io/UX/cal-grant/

**Comment by abquirarte** [comment]
From notes: https://docs.google.com/document/d/1V83tZw6oVT_CpC3_NR7bTjRHDEU4wvFYJSooor2nHRE/edit 

Applying edits to: https://github.com/cagov/UX/issues/85
