### ISSUE TITLE
IA/"California"

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#51]
- [x] Ask PD about when to use "California" in a headline for SEO, specificity, etc.

**Comment by abquirarte** [comment]
I scheduled time with them Tuesday AM before 9am. I have a few things to cover with them, this will be one of them.

**Comment by abquirarte** [comment]
@humancenteredhuman connected with Sarah this week and got the answer. 

**Ans:** leave off the header, include in metadata.
