### ISSUE TITLE
Create DEV page for Release 1 homepage

### ISSUE THREAD

**Issue by abquirarte** [cagov/UX#54]
@artuoma

**Comment by lukefretwell** [comment]
Update suggestions:

- [ ] Change 'Popular' to 'New'
- [ ] Keep all user stories in one column
- [ ] Footer: Use basic white from design system, single line with code below

`State of California &middot; <a href="/about">About</a> &middot; <a href="/news">News</a> &middot; <a href="/feedback">Feedback</a>`

**Comment by lukefretwell** [comment]
@aaronhans @artuoma ☝️

**Comment by abquirarte** [comment]
https://cagov.github.io/Alpha/public/

**Comment by abquirarte** [comment]
@ChadABratton can you add additional documentation this that show's it's done and for easier tracking before I close? Thank you
