### ISSUE TITLE
Make our User Stories for Release 1- Spanish- Main page

### ISSUE THREAD

**Issue by abquirarte** [cagov/UX#55]
### Why
In at least 2 of the 5 prototypes tested, we have come across people that speak Spanish (as their primarily language). As one of the more prominent languages in our state, I would like to test and learn from this:

### Test for

1. Quality/Accuracy of translation API tools
2. Level of effort to validate translations (ask at least 3 native Spanish speakers)
3. Content design from English to Spanish considerations 
4. Domain considerations
5. Level of interest 

### Pages to translate:

- Main Page for Release 1 
- Birth Certificate
- Minimum Wage 
- State Holidays
- Food Banks
- Licensed Contractor

**Comment by abquirarte** [comment]
API ready! 😄

**Comment by abquirarte** [comment]
Top languages to test our top pages for release 1 (@aaronhans )
- Spanish
- Chinese 
- Tagalog 
- Vietnamese
- Korean 
- Persian

**Comment by abquirarte** [comment]
Testing this page: https://cagov.github.io/UX/birth-certificate/es 

Initial comments on the Spanish version: 

- second column: Do they really need a notarized to get a copy?

**Comment by orielgomez** [comment]
A couple of comments on the Spanish vital records page:

first column: 
- change 'Es posible que deba traer una licencia de conducir, pasaporte u otra identificación con foto del gobierno que no haya expirado.' to 'Es posible que debe traer una licencia de manejar, pasaporte o otra forma de identificación del gobierno que no se ha vencido'

- I will find another phrase for 'declaracion jurada' (sworn statement)

third column:
- change 'solicitar en linea' to 'solicitar por internet'

**Comment by abquirarte** [comment]
Example from Austin's Alpha: (also note the banner) https://alpha.austin.gov/en/ 

![image](https://user-images.githubusercontent.com/9556188/71867175-e78dbf00-30bd-11ea-844d-18dc44cf51db.png)

**Comment by abquirarte** [comment]
**Prototypes ready for translation:**

- [ ] - https://cagov.github.io/Alpha/public/es/
- [ ]   https://cagov.github.io/Alpha/public/es/services/california-birth-certificate/
- [ ]   https://cagov.github.io/Alpha/public/es/services/minimum-wage-in-california/
- [ ]   https://cagov.github.io/Alpha/public/es/services/hire-a-licensed-contractor/
- [ ]   https://cagov.github.io/Alpha/public/es/services/find-food-banks-near-you/

**Comment by abquirarte** [comment]
> * [ ]  1. Birth Certificate
> * [ ]  2. Minimum Wage
> * [ ]  3. State Holidays

**Prototypes ready for translation below**

@orielgomez:  Prioritize main page over the other ones for now. 

- [ ]  https://cagov.github.io/Alpha/public/es/
- [ ]  https://cagov.github.io/Alpha/public/es/services/california-birth-certificate/
- [ ]  https://cagov.github.io/Alpha/public/es/services/minimum-wage-in-california/
- [ ]  https://cagov.github.io/Alpha/public/es/services/hire-a-licensed-contractor/
- [ ]  https://cagov.github.io/Alpha/public/es/services/find-food-banks-near-you/

Examples of Spanish sites:

-

**Comment by orielgomez** [comment]
Edits for main page:

Estamos haciendo más fácil de buscar y usar servicios e información del gobierno
Servicios destacados
Encuentra su salario mínimo
Solicitar un acta de nacimiento
Contratar un contratista con licencia para mejorar su hogar
Encuentre los días festivos de empleados estatales de California
Encuentre bancos de alimentos más cercanos

**Comment by orielgomez** [comment]
Attached are translations for minimum wage
[Minimum Wage Spanish Translation.docx](https://github.com/cagov/UX/files/4038776/Minimum.Wage.Spanish.Translation.docx)

**Comment by orielgomez** [comment]
Updated minimum wage page Spanish translation [https://docs.google.com/document/d/e/2PACX-1vSqWwV_1HkOiVO9bAmItiBiHbAz5ESGmWGxsGTXYHIrhyXriWWd3pB_euK13wklmCSEiRU2tHht7RTA/pub](url)

**Comment by orielgomez** [comment]
https://docs.google.com/document/d/e/2PACX-1vSqWwV_1HkOiVO9bAmItiBiHbAz5ESGmWGxsGTXYHIrhyXriWWd3pB_euK13wklmCSEiRU2tHht7RTA/pub

**Comment by orielgomez** [comment]
Updated birth certificate page Spanish translations

https://docs.google.com/document/d/148GXFP9DG208SdosL-WoYLeWQcRkHpS-zLxPfzT3ZaA/edit?usp=sharing

**Comment by orielgomez** [comment]
Updated State holidays Spanish translations
https://docs.google.com/document/d/1ChBZIXoSu2UUPbxHL392uPpBx0JUyDcNuQ30dLjmSSQ/edit?usp=sharing

**Comment by orielgomez** [comment]
Updated homepage Spanish translations

https://docs.google.com/document/d/1mFa7BAJb4CdVO6ly6hb5wiSEObIGzFO2nseo9lwta6A/edit?usp=sharing

**Comment by orielgomez** [comment]
Updated licensed contractor - Spanish translation

https://docs.google.com/document/d/1KY4fsXOzKhKRwK1NfYAcFxVs_A8ckSNAvVjfYsPj9Yo/edit?usp=sharing

**Comment by orielgomez** [comment]
Updated food banks Spanish Translation

https://docs.google.com/document/d/122dJJjdn0NVPRrVUA9tjGpaaI2sQ3qgdQC7G3bITmlg/edit?usp=sharing

**Comment by KimberlyglennTSM** [comment]
closed and approved
