### ISSUE TITLE
Plan 3 co-designing sessions with real users 

### ISSUE THREAD

**Issue by abquirarte** [cagov/UX#60]
To be able to engage a broader audience, we would like to plan at 1-3 engagement/co-design events. This will help us user test content, create new user stories, and gather user insights. 

Working doc, plan: https://docs.google.com/document/d/1DD9cSmmyEbw-grXWgtg7aw_8IBeKXwH_TIgCpOKV17c/edit?ts=5e1766dc# 

- [ ] Come up with a name (service design camp)

- [ ] Meet and discussion questions:
**Purpose:** 
Feedback on existing prototype (more feedback session)
Co-design of user story not yet designed (or one where there is room for iteration) but we pick it
Co-design of user story that the group chooses 
**Duration**: how long should it be?
**Who:**
CFA brigades?
General population in an area 
Specific population specific to the design challenge/user need
How many? Really depends on the above
Who from the core team?
How much **budget** do we have?

**Comment by hilaryhb** [comment]
@abquirarte lets talk about timing and purpose of the co-creation #1

**Comment by abquirarte** [comment]
Closing this. The purpose of this will be served via these two other events: 
- Wildfire visit: https://github.com/cagov/UX/issues/20 
- and the final launch event https://github.com/cagov/UX/issues/79
