### ISSUE TITLE
CONTENT RESEARCH: Independent Worker

### ISSUE THREAD

**Issue by abquirarte** [cagov/UX#61]
Related to #34 

- [x] Create a [spreadsheet. ](https://docs.google.com/spreadsheets/d/1Ts-vLHxeMj8D92r2T1Cl0WAL3iDuDFs0r28wE6QfU_Q/edit#gid=0)
- [x] Reach out to a subject matter expert? (@ )

**Comment by humancenteredhuman** [comment]
@KimberlyglennTSM, @abquirarte, and I reached out to contacts at FTB, and I'll add an issue for follow-up/fact-checking.

**Comment by abquirarte** [comment]
We have ongoing conversations with a few people at FTB. This will now be tracked in the Fact-checking issue.
