### ISSUE TITLE
User Testing: Follow up survey calls (qual)

### ISSUE THREAD

**Issue by hilaryhb** [cagov/UX#62]
Link to main user story Github Issue:

- [x] Email all survey participants who provided email address

- [x] Create [survey](https://www.surveymonkey.com/r/followup916) for those who do not want to have a follow up conversation

- [x] [Schedule willing interviewees](https://docs.google.com/spreadsheets/d/1z83OGux3Ljro14x9HUTtws0-FuDgPkIQ0_ID4800zz8/edit#gid=0)

- [x] Create interview [discussion guide](https://docs.google.com/document/d/12JyEZouVAG_3cwsJ_3m3Fvvo1560H0zR5B9hqYFuvK4/edit#)

- [x] Conduct research calls week of 1/13 and 1/20 - (18 in total)

- [x] Continue final calls week 1/27

- [x] Synthesize and create share out presentation

**Comment by abquirarte** [comment]
Insights from calls:
![20200203_152914](https://user-images.githubusercontent.com/9556188/73700008-31a49900-469a-11ea-91e1-f2143a3ec6d7.jpg)
