### ISSUE TITLE
Content research: Lifeline services

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#66]
- [x] Create a [spreadsheet](https://docs.google.com/spreadsheets/d/1u58pKQgGerhxFbpyxM3wMLwzXIsBbwmDPKT_I7iznvY/edit#gid=0). 
- [x] Reach out to a subject matter expert (@abquirarte )- Michael.Mullaney@cpuc.ca.gov

**Comment by humancenteredhuman** [comment]
@abquirarte reached out to subject matter experts from CPUC. We talked about the application process and eligibility for LifeLine Service, and offered to help out with any fact-checking or follow-up questions.

**Comment by abquirarte** [comment]
Can you link to your notes from yesterday here? (It's ok if it's alpha only access) 😄

**Comment by humancenteredhuman** [comment]
[Google doc of notes from CPUC visit](**url**)

**Comment by abquirarte** [comment]
✅
