### ISSUE TITLE
Content prototype: How to apply for LifeLine services, step by step

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#67]
Main story: #64 

- [x] meta description
- [x] page title
- [x] [Google doc](https://docs.google.com/document/d/1h269a71oOP9nXGTDtj-R5sph4JzqaRLFPsdJ4K9Rq3A/edit#) 
- [ ] Listen to it through a screen reader
- [x] Check for header structure
- [x] URL structure

**Comment by abquirarte** [comment]
https://docs.google.com/document/d/1h269a71oOP9nXGTDtj-R5sph4JzqaRLFPsdJ4K9Rq3A/edit#

**Comment by abquirarte** [comment]
Closing since we have new UX Issue assigned: https://github.com/cagov/UX/issues/82
