### ISSUE TITLE
Content research: Disability insurance benefits

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#69]
Parent issue: #72 

- [x] Create a [spreadsheet](https://docs.google.com/spreadsheets/d/1Qh9d72_F1aKav32hxqhQYIcXgFdTnkRLf6m3D5uR5VI/edit#gid=0). 
- [x] Reach out to a subject matter expert? (@abquirarte  )

**Comment by humancenteredhuman** [comment]
Should we reach out to EDD for fact-checking? @abquirarte @KimberlyglennTSM

**Comment by abquirarte** [comment]
> Should we reach out to EDD for fact-checking? @abquirarte @KimberlyglennTSM

Yeah, what questions do we have? I can at least send to my contact.

**Comment by abquirarte** [comment]
AQ emailed Kevin on 1/27. 

**Email:** 

Hola Kevin!

I hope things are going well with you! 

I wanted to share with you a prototype on disability insurance that our Alpha team put together and we plan to make live in our 2nd release. We like to have some level of fact-checking with our state partners just to make sure the content is being represented accurately. All the prototypes in the Alpha will be assessed after our last release (March) and we'll work with our partners to share lessons learned. 

Who from EDD could verify that this content is accurate? https://cagov.github.io/UX/disability-insurance/ 

Happy to talk through it and catch up soon. Maybe stop by our Alpha space if you'd like? :)
