### ISSUE TITLE
User Story- Vital Records 

### ISSUE THREAD

**Issue by abquirarte** [cagov/UX#7]
As a person that wants to travel abroad
I need to access my birth certificate (vital records)
So that I can get my passport

- [x]  Identify SMEs

- [x] Schedule meeting 

- [x] Baseline what is already there

- [x] (#8) Content research

- [x] (#9) Content prototype

- [x] Meet with SMEs Thursday at 2:30pm. (Prep [Document)](https://docs.google.com/document/d/1XGfUSQ5fO50R_6ZTcMjEx7SjAtKmtNfhoc4JIWVJa1g/edit?usp=sharing)

**Include any of the following, if applicable**
Key contacts/SMEs, what do we think we know, any existing data, potential content types, level of ### complexity

**Comment by hilaryhb** [comment]
Research link: https://github.com/cagov/UX/issues/10#issue-537258138

**Comment by KimberlyglennTSM** [comment]
Reviewed and closed.
