### ISSUE TITLE
Content prototype: Disability insurance benefits

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#71]
#72 

- [x] meta description
- [x] page title
- [x] [Google doc](https://docs.google.com/document/d/1spSR3iE_HXTmhLitwB7ZJ7LxKt0razHrTZVlD1i7zn0/edit#)
- [x] Listen to it through a screen reader
- [x] Check for header structure
- [x] URL structure

**Comment by abquirarte** [comment]
@humancenteredhuman is making one update to the live site to reflect some feedback on step two around the need of knowing whether someone needs to get a permit:

**CSLB baseline:** "According to the California Building Standards Code, no building or structure may be erected, constructed, enlarged, altered, repaired, moved, improved, removed, converted or demolished unless a separate permit for each building or structure has first been obtained from the building official." (edited) 

**City of Sacramento baseline:** "A permit is required for projects such as new construction, additions, remodeling, and repairs to electrical, mechanical, and plumbing systems. Examples include:

- New homes and buildings
- Room additions
- Enclosures and carports
- Decks and patio covers
- Garage conversions
- Landscape irrigation
- Retaining walls
- Window replacements
- Water services
- Sewer services
- Signs
- Water heaters
- Fences
- Fireplaces and fireplace inserts
- Skylights
- Sheds
- Shower/tub enclosure replacements
- Swimming pools and spas
- Re-roofing
- Siding
- Ceiling fans"
- (edited)

**Suggested copy:** "You must buy a building permit with your local building department for new construction, remodeling, or repairs." (edited) 

Then our existing link: Check with your local building department https://www.cslb.ca.gov/Consumers/Hire_A_Contractor/Building_Permit_Requirements.aspx
