### ISSUE TITLE
Fact-checking: Licensed contractor

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#75]
#38 
- [x] @KimberlyglennTSM is following up with CSLB

**Comment by abquirarte** [comment]
Parent user story: https://github.com/cagov/UX/issues/38

**Comment by humancenteredhuman** [comment]
@KimberlyglennTSM found more context around applying for a building permit (at least for city of Sacramento): https://www.cityofsacramento.org/Community-Development/Building/Permits/Required-Permits

**Comment by KimberlyglennTSM** [comment]
Great, thank you so much
*Kimberly Glenn*
Team Success & Delivery Manager
c. 916-270-3515
Kimberly.Glenn@Alpha.ca.gov
Alpha.CA.gov <http://alpha.ca.gov/>
Follow us: Web | Blog | Twitter

**Comment by abquirarte** [comment]
No direct feedback on licensed contractor story from Kimberly's SME.
