### ISSUE TITLE
User Testing: Road Conditions

### ISSUE THREAD

**Issue by abquirarte** [cagov/UX#76]
Link to main user story Github Issue:  https://github.com/cagov/UX/issues/37
Content type being tested: Map
Who is testing and when: Rebecca and Carter tested week of 1/20/2020

**Things to Test for:**
Do people know that we are asking them to input their address and that it's not directions?
Do people want to be alerted?

**Link to insights**
See notes below

** Modifications for Release 2: (as of 2/6 via usertesting.com)

- Accept out of State locations but show error
  - [x] allow autocomplete and text search to find stuff within continental US
  - [x] test retrieved lat,lon and show error if outside of CA
  - [x] do not attempt to retrieve road conditions if start or destination was outside of CA
  - [x] error message should match alert warning at top of calgrants
- [x] Decide on version 1 (single entry field) vs version 2 (both entry fields) - Version 2

- [x] Change the description and title 

- [x] Discuss and agree about disclaimer (traffic, accidents, extreme weather)

- [x] Discuss and agree about moving Get Directions button up - LEAVE as is

- [x] Rebecca please review 2 possible error messages text: out of CA & invalid address

- [x] Discuss and agree on What happens after Get Directions (right now you are dropped into your location) - Need to TEST (Fixed the url that iOS didn't like)

**Comment by abquirarte** [comment]
@carterm please add your notes here :)

**Comment by carterm** [comment]
# Road conditions live user test notes

## Two young women

- They assume when you start typing, the address will appear
- They would use an app like this to "avoid traffic" or "get directions."
- They assume the "Get Alerts" interface is to "get alerts for surprises."
- "Why do I want to sign up for alerts when I want to just get somewhere"
- They are familier with the names of highways

## State worker friends (Man and woman)
- Wants a "Done" button
- Woman owns a 4x4 so is not concerned about chain control
- Woman knows local highways
- Man does not know local highways

## Mike
- Don't need to see two highways
- Get alerts for each highway
- Would rather see a single route
- Would prefer an accordian
- Not interested in just "passes"
- Don't care about routes in San Francisco
- Want to "Open in Maps"

**Comment by abquirarte** [comment]
notes updated ✅

**Comment by aaronhans** [comment]
Thanks @humancenteredhuman this set of changes is complete. We can review latest version with all these fixes now in https://cagov.github.io/UX/caltrans2 and should open new story to migrate to Alpha repo after current release is pushed

**Comment by abquirarte** [comment]
Opening new issue to migrate to Alpha repo: https://github.com/cagov/Alpha/issues/359 
Will also add to "for next week" release 2 checklist
