### ISSUE TITLE
User Testing: Disability Insurance

### ISSUE THREAD

**Issue by abquirarte** [cagov/UX#77]
Link to main user story Github Issue: https://github.com/cagov/UX/issues/72
Content type being tested: Step by step
Who is testing and when: Carter and I tested on Friday, 1/17

**Things to Test for:**
Video?

**Link to insights**

**Comment by humancenteredhuman** [comment]
Hey @carterm would you mind commenting with the user feedback notes you took on your phone? Thanks!

**Comment by carterm** [comment]
# Disability Insurance live user test notes

## Two young women

- The app is for "people who have disabilities"
- Used to get insurance
- They assume you click the "show" button and then follow the steps
- "Why would anybody need this?"
- "Who is this for?"

## State worker friends (Man and woman)
- Noticed the "show" button
- Woman is a state employee who had extra trouble applying in the past.  She had to mail documents to Fresno.  Had to send multiple copies.  She couldn't apply online.  "Everything that could go wrong, went wrong."
- Man wanted to know how they could get ahold of someone to get information.  Wants somewhere to file a complaint.
- Man says the process should be seamless from start to finish
- Suggested a YouTube video with closed captioning to help show the process

**Comment by abquirarte** [comment]
Thank you @carterm ! 

✅ check
