### ISSUE TITLE
UX prototype: Disability insurance benefits 

### ISSUE THREAD

**Issue by artuoma** [cagov/UX#81]
**Parent User Story:** https://github.com/cagov/UX/issues/72
**Prototype Link** https://cagov.github.io/UX/disability-insurance/

- [x] HTML page created and linked in UX repo
- [x] Meta description added
- [x] Page title updated
- [x] Content integrated according to design system and standards 
- [x] Automated accessibility checks performed (score of 100%)
- [x] Manual accessibility checks performed ([See checklist](https://drive.google.com/open?id=0B72FqFUONAggazJwQURQeTBPMEZGRjJXSFNGcDJrMF9ENERR))
- [x] HTML structure verified
- [x] Design issue template # (Closed)
- [ ] Migrated to Alpha repo

**11y Status:** Issues and resolution status if applicable
- A11y issue with step by step accordion, pending resolution 
- HTML structure causing issue, pending resolution 

**Design Issue Link:** Link to Design issue if applicable#

**Comment by artuoma** [comment]
A11y issue with step by step accordion, resolution pending.

**Comment by lukefretwell** [comment]
@artuoma this looks great. 

Would be great to address this in tandem so we can see what it looks like in context:

https://github.com/cagov/cwds/issues/20

**Comment by abquirarte** [comment]
Closing, though it still needs to be migrated to Alpha repo. Is there a new issue for it?
