### ISSUE TITLE
UX prototype: How to apply for California LifeLine services

### ISSUE THREAD

**Issue by artuoma** [cagov/UX#82]
**Parent User Story:** https://github.com/cagov/UX/issues/64

**content prototypes:** 
#67

**Prototype Link(s):** 
-- https://cagov.github.io/UX/apply-discounted-phone-service/

- [x] HTML page(s) created and linked in UX repo
- [x] Meta description added 
- [x] Page title updated
- [ ] Content integrated according to design system and standards 
- [ ] Automated accessibility checks performed (score of 100%)
- [ ] Manual accessibility checks performed ([See checklist](https://drive.google.com/open?id=0B72FqFUONAggazJwQURQeTBPMEZGRjJXSFNGcDJrMF9ENERR))
- [ ] HTML structure verified
- [ ] Design issue template # (Closed)
- [ ] Migrated to Alpha repo

**11y Status:** Issues and resolution status if applicable

**Design Issue Link:** Link to Design issue if applicable#

**Functionality work:** https://github.com/cagov/UX/issues/115

**Comment by abquirarte** [comment]
@artuoma note the content prototypes 👇 

https://github.com/cagov/UX/issues/106 
https://github.com/cagov/UX/issues/105 
https://github.com/cagov/UX/issues/67

**Comment by abquirarte** [comment]
closing for this iteration
