### ISSUE TITLE
UX Design issue: Step-by-step tweaks

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/UX#84]
- [x] Link to UX page (if applicable)
https://cagov.github.io/UX/cal-grant/
https://cagov.github.io/UX/disability-insurance/
https://cagov.github.io/UX/apply-discounted-phone-service/
https://alpha.ca.gov/services/hire-licensed-contractor-home-improvements/

- [x] In Firefox browser doesn't consistently expand to the correct height (refresh several times to reproduce)
- [x] On individual steps, "More info" instead of "Show"
- [x] Somewhere on top of the steps, "Show all details"

**Comment by artuoma** [comment]
Firefox Bug: ![Screen Shot 2020-02-13 at 10 30 10 AM](https://user-images.githubusercontent.com/20782462/74466335-d5850600-4e4b-11ea-9ca9-406eb7424438.png)

**Comment by artuoma** [comment]
@aaronhans (Firefox Bug)

**Comment by artuoma** [comment]
@carterm (Expand all)

**Comment by aaronhans** [comment]
I've been messing around with this and haven't found the root of the problem yet but I cannot reproduce it in the Alpha repository every. Here is the Cal Grant page there: https://staging.alpha.technology.ca.gov/apply-for-cal-grant/ I am able to reliably reproduce it in the UX repo if I hit refresh a few times in Firefox

**Comment by abquirarte** [comment]
The same thing happened when user testing this weekend. On a Chrome browser, using Kimberly's Surface Tablet. (see picture) 

![20200215_110704](https://user-images.githubusercontent.com/9556188/74688370-2bc7b100-518c-11ea-87ed-b28dee1cf26c.jpg)

**Comment by aaronhans** [comment]
I've got this sorted out now, added timeouts so the initial animations don't get destroyed by browser command batching too
