### ISSUE TITLE
UX Design issue: Apply for a CalGrant

### ISSUE THREAD

**Issue by artuoma** [cagov/UX#85]
- [x] Content organization reviewed from Design perspective 
- [x] User interaction discussed and documented 
- [x] Wireframes iterated and finalized (If applicable)
- [x] Design system discrepancies minimized
- [x] Design and UX issues documented and resolved

**Links to parent prototype issue(s)**
- https://github.com/cagov/UX/issues/83

**Link to UX prototype or CWDS template page(s)**
- https://cagov.github.io/UX/cal-grant/

**Comments on content information architecture and Organization**
- Comments:

**Wireframe comments and location**
- Applicable link(s)
- Comments:

**User interaction feedback and links**

- On index.html
     - [x] Changing checklist to bullet points 
     - [x] Putting "Who can get a Cal Grant" in an accordion
     - [x] Making deadline alert stand out
- On step-1.html
     - [x] Making deadline alert stand out
     - [x] Moving FAFSA before CADAA in the tables (FAFSA is the more common application)
- On step-2.html
     - [x]  Putting "Before you submit your form" in an accordion
     - [x]  Putting "When to submit test scores instead of your GPA" in an accordion
     - [x] Making deadline alert stand out
- On finish.html
     - [x] Changing checklist to bullet points 

**Design system issues**
- Applicable link(s)
- Comments:

**Comment by abquirarte** [comment]
- [ ] Fix accordion from step 2 (Aaron working on it)
- [ ]  2nd set of eyes (AQ and Oriel to look)

**Comment by abquirarte** [comment]
Closing. Next Steps tracked in: https://github.com/cagov/UX/issues/83
