### ISSUE TITLE
UX prototype: Road Conditions

### ISSUE THREAD

**Issue by artuoma** [cagov/UX#86]
**Parent User Story:** https://github.com/cagov/UX/issues/37
**Prototype Link(s):** https://cagov.github.io/UX/caltrans/

- [x] HTML page(s) created and linked in UX repo
- [x] Meta description added 
- [x] Page title updated
- [x] Content integrated according to design system and standards 
- [x] Automated accessibility checks performed (score of 100%)
- [x] Manual accessibility checks performed ([See checklist](https://drive.google.com/open?id=0B72FqFUONAggazJwQURQeTBPMEZGRjJXSFNGcDJrMF9ENERR))
- [x] HTML structure verified
- [x] Design issue template # (Closed)
- [x] Migrated to Alpha repo

**11y Status:** Issues and resolution status if applicable

**Design Issue Link:** Link to Design issue if applicable#

**Comment by hilaryhb** [comment]
@aaronhans can you add error messaging around if the beginning or end destination is outside of CA?

**Comment by KimberlyglennTSM** [comment]
Road Conditions - Shipped on 2/10/2020
