### ISSUE TITLE
UX prototype: Find my water quality

### ISSUE THREAD

**Issue by artuoma** [cagov/UX#87]
**Parent User Story:** Link to parent user story
**Prototype Link(s):** Link to UX prototype page

- [ ] Wireframes iterated and finalized (If applicable)
- [ ] HTML page(s) created and linked in UX repo
- [ ] Meta description added 
- [ ] Page title updated
- [ ] Content integrated according to design system and standards 
- [ ] Automated accessibility checks performed (score of 100%)
- [ ] Manual accessibility checks performed ([See checklist](https://drive.google.com/open?id=0B72FqFUONAggazJwQURQeTBPMEZGRjJXSFNGcDJrMF9ENERR))
- [ ] HTML structure verified
- [ ] Design issue template # (Closed)
- [ ] Migrated to Alpha repo

**11y Status:** Issues and resolution status if applicable

**Design Issue Link:** Link to Design issue if applicable#

**Comment by abquirarte** [comment]
closing for this iteration
