### ISSUE TITLE
User Testing: Road Conditions 2

### ISSUE THREAD

**Issue by abquirarte** [cagov/UX#91]
Main story: https://github.com/cagov/UX/issues/37 

related: #86 

CC: @aaronhans @artuoma @orielgomez @KimberlyglennTSM 

## Updates before user testing:
- [x] Removing "next"
- [x] Add explainer text to what you can enter (zip code)
- [x] Add explainer about road conditions
- [x] Confirm what users put in, if they don't put in direct address: "Your starting address" "Your destination address"
- [x] Make seachbox wider
- [x] Need to only ask one question or input at a time, do not show starting point address from the beginning (See Wireframe: https://drive.google.com/drive/u/0/folders/1v387TyaG1qyCzOKnDEH22FLIse8chv_x)

## Content type being tested: 
Smart Answer

## **Things to Test for:**
Do people want to get an alert? 
Do they know this is not about traffic "what does road conditions mean to them?"

## **Link to insights (after user testing)**
- [x] Link the notes from Road Conditions Testing on 01/31/2020 https://docs.google.com/document/d/1PY0c1R-aPWnaY0_PIfm3stLl8WLCsfrZajTVn2kY7YQ/edit

**Comment by aaronhans** [comment]
- [ ] add autocomplete
- [ ] add locate me
- [ ] add space above results
- [ ] scroll to results after 2nd choice
- [ ] add buttons
- [ ] add locate me
- [ ] limit autocomplete results to destinations in CA
- [ ] add calls to road closures
- [ ] add calls to CHP incidents

**Comment by aaronhans** [comment]
Moving the following undone items to issue #104 
- [ ] Add error message for when a user enters saldfjhdskjfh: "Please enter a valid city or zip code, such as San Francisco or 95818."
- [ ] Add disclaimer message for when a user enters in an address outside of California: "Please note: We can only share the road conditions on the part of your trip within California."

**Comment by abquirarte** [comment]
thank you for consolidating @aaronhans !
