### ISSUE TITLE
Draft Lessons Learned from Independent Worker User Story

### ISSUE THREAD

**Issue by abquirarte** [cagov/UX#97]
While we will not be prototyping something for the independent worker user story, I think it's important that we capture our team lessons learned in pursuing this story. 

Main Story: https://github.com/cagov/UX/issues/34 

![20200127_115530](https://user-images.githubusercontent.com/9556188/73503425-14618900-4381-11ea-93ad-2a689a456bc6.jpg)

CC: @humancenteredhuman 

[Google doc on lessons learned](https://docs.google.com/document/d/1_hoGmFlJajeqdvrnViAlvG8EaA_IhwAwaXW-1AQ5GCo/edit?usp=sharing)

**Comment by KimberlyglennTSM** [comment]
Great write-up @humancenteredhuman
